# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 1, 18, 30, 53, 776000, tzinfo=utc)),
        ),
    ]
