# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0002_auto_20160802_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
