# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0004_auto_20160802_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 1, 18, 44, 2, 974000, tzinfo=utc)),
        ),
    ]
