# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0008_auto_20160802_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 2, 15, 3, 17, 650000, tzinfo=utc)),
        ),
    ]
